### ISSUE TITLE
upgrade from rn-fetch-blob to react-native-blob-util

### ISSUE THREAD

**Issue by konri** [jpalumickas/react-native-activestorage#15]
Hi, 
Are you planing to upgrade to react-native-blob-util. I cannot have both library in build because I got the error while building and in stackoverflow I found that react-native cannot have these two libraries together and newer version of libraries are using react-native-blob-util. 
Thanks

**Comment by JDGarner** [comment]
I've opened a PR for this - https://github.com/jpalumickas/react-native-activestorage/pull/17
