### ISSUE TITLE
cannot compile with rn-fetch-blob

### ISSUE THREAD

**Issue by vcavallo** [jpalumickas/react-native-activestorage#9]
```
[[my-project-directory]]/node_modules/rn-fetch-blob/index.js 12:12
Module parse failed: Unexpected token (12:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   AppState,
| } from 'react-native'
> import type {
|   RNFetchBlobNative,
|   RNFetchBlobConfig,
```

Also, the linked `rn-fetch-blob` in the readme is a 404: https://github.com/jpalumickas/react-native-activestorage/blob/master/rn-fetch-blob

**Comment by jpalumickas** [comment]
Hey @vcavallo,

I think this issue related to rn-fetch-blob itself. Maybe you can find some related information in their issues.

In the future, I think we need to replace this with new fork https://github.com/RonRadtke/react-native-blob-util

**Comment by jpalumickas** [comment]
This package now requires react-native-blob-util
